#!/usr/bin/env bash
# Snapshot Claude Code's project memory into the repo so it survives a lost
# machine, a wiped ~/.claude, or a fresh session on another box.
#
# The live memory lives OUTSIDE this repo, at
#   ~/.claude/projects/-Users-williamstewart2-butterflydreaming-graphviewer1/memory/
# so `git push` never backs it up. This script concatenates every memory file
# into MEMORY_SNAPSHOT.md at the repo root, where it is version-controlled.
#
#   ./sync_memory_snapshot.sh          # regenerate the snapshot
#   ./sync_memory_snapshot.sh --check  # exit 1 if the snapshot is stale
#
# To RESTORE: see the "Restoring" section at the top of MEMORY_SNAPSHOT.md.
set -euo pipefail

MEM="$HOME/.claude/projects/-Users-williamstewart2-butterflydreaming-graphviewer1/memory"
OUT="$(cd "$(dirname "$0")" && pwd)/MEMORY_SNAPSHOT.md"

[ -d "$MEM" ] || { echo "No memory directory at $MEM" >&2; exit 1; }

TMP="$(mktemp)"
{
  echo "# Memory snapshot — ButterflyDreaming graph viewer"
  echo
  echo "Generated by \`sync_memory_snapshot.sh\` on $(date '+%Y-%m-%d %H:%M'). **Do not hand-edit** —"
  echo "edit the live memory files and re-run the script, or your changes are lost on the"
  echo "next sync."
  echo
  echo "## What this is"
  echo
  echo "Claude Code keeps per-project memory as one Markdown file per fact, in"
  echo "\`~/.claude/projects/-Users-williamstewart2-butterflydreaming-graphviewer1/memory/\`."
  echo "\`MEMORY.md\` there is the index loaded into context at the start of every session."
  echo "That directory is **outside this repo and not in git**, so pushing the code does not"
  echo "back it up. This file is the backup."
  echo
  echo "## Restoring after a new machine / wiped ~/.claude"
  echo
  echo "Each `## FILE:` section below is one memory file, named in its heading. Recreate the directory"
  echo "above and write each section back to its filename (frontmatter included, starting at"
  echo "the \`---\` line). \`MEMORY.md\` is the index and must be restored too. Then start a"
  echo "session in this repo and the memories load automatically."
  echo
  echo "Sections: $(find "$MEM" -maxdepth 1 -name '*.md' | wc -l | tr -d ' ') files."
  echo
  echo "---"
  for f in "$MEM"/MEMORY.md "$MEM"/*.md; do
    b="$(basename "$f")"
    case " ${seen:-} " in *" $b "*) continue;; esac
    seen="${seen:-} $b"
    echo
    echo "## FILE: $b"
    echo
    echo '```markdown'
    cat "$f"
    echo '```'
    echo
    echo "---"
  done
} > "$TMP"

if [ "${1:-}" = "--check" ]; then
  if cmp -s "$TMP" "$OUT"; then echo "snapshot up to date"; rm -f "$TMP"; exit 0
  else echo "MEMORY_SNAPSHOT.md is STALE — run ./sync_memory_snapshot.sh" >&2; rm -f "$TMP"; exit 1; fi
fi

mv "$TMP" "$OUT"
echo "wrote $OUT ($(wc -l < "$OUT" | tr -d ' ') lines)"
