#!/usr/bin/env python3
"""Regenerate sources/manifest.json from whatever is in sources/.

WHY THIS EXISTS. The module needs a list of the samples it can offer, and a
browser cannot read a directory — there is no filesystem API from a page, and
express.static does not serve an index. So the directory listing has to be
MADE AHEAD OF TIME and fetched as data. This script is that step.

A manifest rather than a server endpoint on purpose: an endpoint would work in
BD and fail in a standalone on GitHub Pages, and the standalone is the whole
point of publishing these modules.

Run it after adding or removing a sample:

    python3 make_manifest.py

SHIPPING FORMAT IS MP3. A .wav is NEVER listed, whether or not an .mp3 of the
same stem exists: wavs here are working masters, are gitignored, and are not
offered to the module. A sample library compounds: the cosmic pad alone is
11.5 MB lossless against 1.0 MB at 128 kbps, and the material granular wants
(steady, no transients) is exactly the material a codec handles best.
"""
import hashlib, json, os, re, subprocess, sys

HERE    = os.path.dirname(os.path.abspath(__file__))
SOURCES = os.path.join(HERE, 'sources')
# SHIPPABLE FORMATS ONLY. .wav is deliberately absent: the raw masters live in
# this directory, are gitignored, and are not what the module should offer —
# the unprocessed 6.5 MB vox source was briefly listed as a playable sample
# because .wav was in this list and no .mp3 of that stem existed yet.
PREFER  = ['.mp3', '.m4a']

def slug(name):
    """A stable id for a script to name. Filenames carry spaces, capitals and
    duplicated underscores; a directive value must not depend on any of that,
    so the script says `%%bd_sample pad_in_love_a_min_2` whatever the file is
    called. It also means a file can be renamed without breaking saved scripts."""
    s = re.sub(r'[^a-z0-9]+', '_', name.lower()).strip('_')
    return re.sub(r'_+', '_', s)

def duration(path):
    try:
        out = subprocess.run(['afinfo', path], capture_output=True, text=True).stdout
        m = re.search(r'estimated duration:\s*([\d.]+)', out)
        return round(float(m.group(1)), 2) if m else None
    except Exception:
        return None

def main():
    by_stem = {}
    for fn in sorted(os.listdir(SOURCES)):
        stem, ext = os.path.splitext(fn)
        if ext.lower() not in PREFER:
            continue
        by_stem.setdefault(slug(stem), []).append((ext.lower(), fn))

    entries = []
    for sid, files in sorted(by_stem.items()):
        files.sort(key=lambda p: PREFER.index(p[0]))
        ext, fn = files[0]
        skipped = [f for e, f in files[1:]]
        path = os.path.join(SOURCES, fn)
        # A CONTENT HASH, so the module can version the URL it asks for.
        #
        # Without it a changed sample may never reach anyone. Locally the MP3s
        # go out as `public, max-age=0` and it is up to the browser whether to
        # revalidate; published to GitHub Pages they sit behind a CDN that will
        # happily pin the old bytes for a long time. The symptom is the worst
        # kind: the page is demonstrably new — the canary changed — and the
        # SOUND is the old one, so you doubt the edit rather than the cache.
        # Exactly why AV/kolam.html versions its renderer.
        with open(path, 'rb') as fh:
            digest = hashlib.sha256(fh.read()).hexdigest()[:10]
        entries.append({
            'id':       sid,
            'file':     fn,
            'v':        digest,
            'label':    sid.replace('_', ' '),
            'bytes':    os.path.getsize(path),
            'seconds':  duration(path),
        })
        note = ('  (ignoring ' + ', '.join(skipped) + ')') if skipped else ''
        print('  %-26s %-34s %7.0f KB%s' % (sid, fn, os.path.getsize(path)/1024, note))

    out = {
        '_comment': 'Generated by make_manifest.py — do not edit by hand. '
                    'Licence and provenance for each entry live in SOURCES.md.',
        'samples': entries,
    }
    with open(os.path.join(SOURCES, 'manifest.json'), 'w') as f:
        json.dump(out, f, indent=2)
        f.write('\n')
    print('\nwrote sources/manifest.json — %d sample%s' % (len(entries), '' if len(entries)==1 else 's'))

if __name__ == '__main__':
    main()
